### ISSUE TITLE
Error notifications

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/jupyter-rs-radia#25]
Jupyter tends to swallow python exceptions and so fail silently when they occur.  ```print()``` also fails a lot of the time.  We need to at least inform the user of things like invalid files etc.

**Comment by robnagler** [comment]
If you use pkdlog, it will notice if IPython is running and call get_ipython().write_err. 

I'm sure you would never use a [naked print](https://github.com/radiasoft/pykern/wiki/DesignHints#output-for-programmers-logging) in our code. :)

**Comment by mkeilman** [comment]
FYI:
```DeprecationWarning: InteractiveShell.write_err() is deprecated, use sys.stderr instead```

**Comment by robnagler** [comment]
Interesting. [The code](https://github.com/radiasoft/pykern/blob/29f6588dee3d19e6b68929cc0a76f8e958cde892/pykern/pkdebug.py#L86) will work correctly when the routine is finally removed, because it is a feature test:

```py
#: Get IPython InteractiveShell.write()
# See https://github.com/ipython/ipython/blob/master/IPython/core/interactiveshell.py)
_ipython_write = None
try:
    _ipython_write = get_ipython().write_err
except Exception:
    pass
```

**Comment by mkeilman** [comment]
So pkdlog did not work either, and the reason is that [widgets mess things up](https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget). I'm using the capture method they outline in the link
