### ISSUE TITLE
error in using RadiaViewer from Example 5

### ISSUE THREAD

**Issue by bnash** [radiasoft/jupyter-rs-radia#34]
When executing Radia_Ex05-widget, I get the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/jupyter_rs_radia/json/schema.json'`

**Comment by robnagler** [comment]
@mkeilman it looks like 47917a4 was reverted. Would you look into it?

**Comment by mkeilman** [comment]
Checking it out now

**Comment by mkeilman** [comment]
(The reason the commit was reverted is that my local clone does not include it, so the changes got clobbered)

**Comment by robnagler** [comment]
You should have gotten a merge conflict.
